import { Inter } from "next/font/google";
import { Poppins } from 'next/font/google';
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter",});
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: "--body-poppins",
});


export const metadata = {
  title: "Movis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable} bg-neutral pt-3`}>
      <head>
        <link rel="favicon" href="/favicon.png"></link>
      </head>
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
